# Generated by Django 2.0.8 on 2018-09-04 12:05

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailtrans', '0007_auto_20180327_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type', models.CharField(choices=[('main_menu', 'Main menu'), ('meta_menu', 'Meta menu'), ('footer_menu', 'Footer menu')], default='main_menu', max_length=255)),
                ('header_logo_link', models.CharField(blank=True, help_text='This link is used to link the header logo.', max_length=255, null=True, verbose_name='Header logo link')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu', to='wagtailtrans.Language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('target_appendix', models.CharField(blank=True, help_text='If needed you could append a string to the url, e.g. a hash.', max_length=255, null=True, verbose_name='Link appendix')),
                ('_name', models.CharField(blank=True, help_text="If left empty, the target's title will be used.", max_length=255, null=True, verbose_name='Alt. name')),
                ('submenu', wagtail.core.fields.StreamField([('page_link', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.PageChooserBlock())])), ('jump_link', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('link', wagtail.core.blocks.CharBlock())])), ('external_link', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.URLBlock())]))], blank=True, null=True)),
                ('menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='contrib.Menu')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
    ]
