# Generated by Django 2.0.8 on 2018-09-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='header_logo_link',
        ),
    ]
