# Generated by Django 2.0.8 on 2018-09-19 09:28

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0002_remove_menu_header_logo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='submenu',
            field=wagtail.core.fields.StreamField([('page_link', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='If left empty the title of the page is used', required=False)), ('page', wagtail.core.blocks.PageChooserBlock())])), ('jump_link', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('link', wagtail.core.blocks.CharBlock())])), ('external_link', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.URLBlock())]))], blank=True, null=True),
        ),
    ]
