# Generated by Django 2.0.8 on 2018-09-03 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailtrans', '0007_auto_20180327_1127'),
        ('wagtailcore', '0040_page_draft_title'),
        ('cms', '0002_homepageimageitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDiaryEntry',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='wagtailcore.Page')),
                ('translatablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailtrans.TranslatablePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailtrans.translatablepage', 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ProjectDiaryOverview',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='wagtailcore.Page')),
                ('translatablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailtrans.TranslatablePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailtrans.translatablepage', 'wagtailcore.page'),
        ),
    ]
