# Generated by Django 2.0.8 on 2018-09-03 14:18

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('taggit', '0002_auto_20150616_2121'),
        ('cms', '0003_projectdiaryentry_projectdiaryoverview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDiaryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='projectdiaryentry',
            name='content',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdiaryentry',
            name='teaser_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='wagtailimages.Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectdiarytag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_tags', to='cms.ProjectDiaryEntry'),
        ),
        migrations.AddField(
            model_name='projectdiarytag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_projectdiarytag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='projectdiaryentry',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='cms.ProjectDiaryTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
