# Generated by Django 2.0.8 on 2018-09-04 11:06

import cireg.cms.blocks
from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20180903_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdiaryentry',
            name='pinned_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectdiaryentry',
            name='content',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('icon_heading_block', cireg.cms.blocks.IconHeadingBlock())], blank=True, null=True),
        ),
    ]
