# Generated by Django 2.0.8 on 2018-09-04 11:18

import cireg.cms.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('wagtailtrans', '0007_auto_20180327_1127'),
        ('wagtailcore', '0040_page_draft_title'),
        ('cms', '0005_auto_20180904_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='wagtailcore.Page')),
                ('translatablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailtrans.TranslatablePage')),
                ('content', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('intro_text', wagtail.core.blocks.RichTextBlock()), ('icon_heading_block', cireg.cms.blocks.IconHeadingBlock()), ('heading_block', cireg.cms.blocks.HeadingBlock()), ('text_and_fact_block', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock()), ('facts', wagtail.core.blocks.ListBlock(cireg.cms.blocks.FactBlock))]))], blank=True, null=True)),
                ('teaser_image', models.ForeignKey(help_text='This image is used for the teaser boxes at the homepage.', on_delete=django.db.models.deletion.PROTECT, to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailtrans.translatablepage', 'wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='projectdiaryentry',
            name='content',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('icon_heading_block', cireg.cms.blocks.IconHeadingBlock()), ('heading_block', cireg.cms.blocks.HeadingBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdiaryentry',
            name='pinned_post',
            field=models.BooleanField(default=False, help_text='If selected this post will be the first post at the homepage.'),
        ),
        migrations.AlterField(
            model_name='projectdiaryentry',
            name='teaser_image',
            field=models.ForeignKey(help_text='This image is used for the teaser boxes at the homepage.', on_delete=django.db.models.deletion.PROTECT, to='wagtailimages.Image'),
        ),
    ]
