# Generated by Django 2.0.8 on 2018-09-04 11:31

import cireg.cms.blocks
from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_contentpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdiaryentry',
            name='teaser_text',
            field=models.TextField(default='teaser text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='content',
            field=wagtail.core.fields.StreamField([('icon_heading_block', cireg.cms.blocks.IconHeadingBlock()), ('heading_block', cireg.cms.blocks.HeadingBlock()), ('text', wagtail.core.blocks.RichTextBlock()), ('intro_text', wagtail.core.blocks.RichTextBlock()), ('text_and_fact_block', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock()), ('facts', wagtail.core.blocks.ListBlock(cireg.cms.blocks.FactBlock))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='content',
            field=wagtail.core.fields.StreamField([('icon_heading_block', cireg.cms.blocks.IconHeadingBlock()), ('heading_block', cireg.cms.blocks.HeadingBlock()), ('text', wagtail.core.blocks.RichTextBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdiaryentry',
            name='content',
            field=wagtail.core.fields.StreamField([('icon_heading_block', cireg.cms.blocks.IconHeadingBlock()), ('heading_block', cireg.cms.blocks.HeadingBlock()), ('text', wagtail.core.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
