# Generated by Django 2.0.8 on 2018-09-12 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailtrans', '0007_auto_20180327_1127'),
        ('wagtaildocs', '0008_document_file_size'),
        ('wagtailimages', '0021_image_file_hash'),
        ('cms', '0010_auto_20180912_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadItem',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description', models.TextField()),
                ('energy_type', models.CharField(blank=True, choices=[('solar', 'Solar'), ('wind', 'Wind'), ('hydro', 'Hydro')], max_length=20, null=True)),
                ('timestamp', models.CharField(blank=True, choices=[('historical', 'Historical'), ('future', 'Future')], max_length=20, null=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtaildocs.Document')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DownloadOverviewPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='wagtailcore.Page')),
                ('translatablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailtrans.TranslatablePage')),
                ('show_filter', models.BooleanField(default=True)),
                ('intro_text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailtrans.translatablepage', 'wagtailcore.page'),
        ),
    ]
