# Generated by Django 2.0.8 on 2018-09-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_downloaditem_downloadoverviewpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadoverviewpage',
            name='intro_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
