# Generated by Django 2.0.8 on 2018-09-12 10:39

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20180912_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='downloaditem',
            name='energy_type',
        ),
        migrations.AddField(
            model_name='downloaditem',
            name='energy_type',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='cms.EnergyType'),
        ),
    ]
