# Generated by Django 2.0.8 on 2018-09-12 12:10

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20180912_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadoverviewpage',
            name='intro_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
