# Generated by Django 2.0.8 on 2018-09-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20180912_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloaditem',
            name='file_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
