# Generated by Django 2.0.8 on 2018-09-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_downloaditem_file_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudy',
            old_name='location',
            new_name='subtitle',
        ),
    ]
