# Generated by Django 2.0.8 on 2018-09-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_auto_20180919_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_source',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Source for text'),
        ),
    ]
