# Generated by Django 2.0.8 on 2018-09-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_homepage_hero_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_source',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_text_source',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Source for hero text'),
        ),
    ]
